### ISSUE TITLE
Request : FBCSP code

### ISSUE THREAD

**Issue by mouadriyad** [vlawhern/arl-eegmodels#10]
Hi,

Could you share with us your FBCSP implementation?

**Comment by mouadriyad** [comment]
Hi could you share with us your implementation of the FBCSP because mine (based on mne and SKlearn) get always bad accuracy.

**Comment by vlawhern** [comment]
My original FBCSP code was written in MATLAB and would require a lot of rewriting to make it usable more generally. Perhaps you can try to use this package here, it seems to be pretty well-documented:

https://github.com/MultiScale-BCI/IV-2a

**Comment by mouadriyad** [comment]
I couldn't create a valid model with same performances but I solved it.

**Comment by robintibor** [comment]
In shameless self promotion you could also have a look at our fbcsp implementation :D https://github.com/TNTLFreiburg/fbcsp as used in https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.23730

**Comment by mouadriyad** [comment]
> In shameless self promotion you could also have a look at our fbcsp implementation :D https://github.com/TNTLFreiburg/fbcsp as used in https://onlinelibrary.wiley.com/doi/full/10.1002/hbm.23730

I will be glad to check your implementation, every help is welcome
