### ISSUE TITLE
Error with the Example

### ISSUE THREAD

**Issue by Khalizo** [vlawhern/arl-eegmodels#20]
I tried to run the example file ("ERP.py"), but got this error: 
![image](https://user-images.githubusercontent.com/22616237/87070233-664fea00-c210-11ea-94f6-7c6a099d4d16.png)

Please can you help with this?

**Comment by vlawhern** [comment]
That's caused by not having the correct 'image_data_format' variable.. see #13

**Comment by Khalizo** [comment]
Thanks for your reply, I will have a look and let you know if i have any
questions.
