### ISSUE TITLE
The implement of PyTorch

### ISSUE THREAD

**Issue by BIRlz** [vlawhern/arl-eegmodels#24]
I am wondering whether you would release a pytorch implement of this repo? If possibile, it will be a great convenient for us!

**Comment by vlawhern** [comment]
All of the models implemented here are also implemented in the `braindecode` package (which uses PyTorch as the backend), available at https://github.com/braindecode/braindecode

**Comment by BIRlz** [comment]
> All of the models implemented here are also implemented in the `braindecode` package (which uses PyTorch as the backend), available at https://github.com/braindecode/braindecode

Thinks for your work and reply!
Have a nice day!
