### ISSUE TITLE
installing EEGLearn in google colab

### ISSUE THREAD

**Issue by hmdmolaei** [vlawhern/arl-eegmodels#30]
I tried to install this library in colab using pip install command, however I faced the following error:

ERROR: Cannot unpack file /tmp/pip-unpack-vxbd6gy5/EEGLearn.git (downloaded from /tmp/pip-req-build-eq0fmo3q, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-eq0fmo3q

how can I solve this?

**Comment by vlawhern** [comment]
I believe you posted this to the wrong repo? This should go to the EEGLearn repository (https://github.com/pbashivan/EEGLearn)..

**Comment by hadyabdullah** [comment]
ModuleNotFoundError: No module named 'EEGModels' in this from EEGModels import EEGNet what should i do
