### ISSUE TITLE
Dimension error EEGnet

### ISSUE THREAD

**Issue by Cerebrock** [vlawhern/arl-eegmodels#5]
InvalidArgumentError: Negative dimension size caused by subtracting 64 from 1 for 'depthwise_conv2d_1/depthwise' (op: 'DepthwiseConv2dNative') with input shapes: [?,1,64,4], [64,1,4,2].
:S

**Comment by robintibor** [comment]
It might have to do with the image_data_format, see https://github.com/vlawhern/arl-eegmodels/blob/4558da71f87ac14299ea131c230f950de38de5d9/EEGModels.py#L7
If you try changing it, does it help?

**Comment by Cerebrock** [comment]
I tried both reshaping the input and changing the order of the parameters in the conv layers. With the modification of the json file I get a new error. 
![image](https://user-images.githubusercontent.com/20531340/43051060-84b8467a-8de9-11e8-9c30-4a727060dc57.png)

ValueError: Error when checking target: expected softmax to have shape (11,) but got array with shape (1,)

**Comment by vlawhern** [comment]
You need to do the one-hot encoding of the class labels for multi-class classification; i.e.: an 11-column matrix of 0's and 1's indicating the class membership. To do this easily you can use a function found inside of keras:

`tf.keras.utils.to_categorical`

**Comment by Cerebrock** [comment]
I was skipping the cell with the one-hot, its running now!!! :D. The issue at first was the change in the .json file, why not use TF default ordering? Thank you guys!

**Comment by vlawhern** [comment]
It was a habit back when I was using Keras with Theano, as Theano used NCHW (samples, channels, height, width) as default, whereas Tensorflow uses NHWC. I have a version of this code that checks for the users ordering and builds the model according to that but I haven't pushed it yet.

Let me know if there are any other issues!
