### ISSUE TITLE
Cite MNE

### ISSUE THREAD

**Issue by agramfort** [vlawhern/arl-eegmodels#9]
hi,

thanks a lot for this great work. I see that you use MNE for you work. It would be really appreciated if you could properly cite MNE in your papers: http://martinos.org/mne/stable/faq.html#cite so we can continue to get funding for this project by justifying of its actual impact.

thanks a lot
Alex

**Comment by vlawhern** [comment]
My apologies. I have updated the sample script in this package with the needed citations to MNE (in addition to PyRiemann and several other papers). 

I have not yet published any papers that use MNE, however if I do I will be sure to include the necessary references as requested.

Please let me know if this sufficiently addresses your concerns. I'm more than happy to make any additional changes to this repository as needed.

**Comment by agramfort** [comment]
thanks a lot.
